apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: pushgateway
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
