apiVersion: apps/v1
kind: Deployment
metadata:
  name: soil-sensor-q1-001
  namespace: soil-sensor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soil-sensor-q1-001
  template:
    metadata:
      labels:
        app: soil-sensor-q1-001
    spec:
      containers:
      - name: soil-sensor
        image: fariaass/soil-sensor:v1.0
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
        env:
        - name: Sensor__MinIntervalSeconds
          valueFrom:
            configMapKeyRef:
              name: soil-sensor-base-config
              key: SENSOR_MIN_INTERVAL
        - name: Sensor__MaxIntervalSeconds
          valueFrom:
            configMapKeyRef:
              name: soil-sensor-base-config
              key: SENSOR_MAX_INTERVAL
        - name: Sensor__Location
          value: "q1"
        - name: Sensor__SensorId
          value: "soil-monitor-q1-001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soil-sensor-q2-001
  namespace: soil-sensor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soil-sensor-q2-001
  template:
    metadata:
      labels:
        app: soil-sensor-q2-001
    spec:
      containers:
      - name: soil-sensor
        image: fariaass/soil-sensor:v1.0
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
        env:
        - name: Sensor__MinIntervalSeconds
          valueFrom:
            configMapKeyRef:
              name: soil-sensor-base-config
              key: SENSOR_MIN_INTERVAL
        - name: Sensor__MaxIntervalSeconds
          valueFrom:
            configMapKeyRef:
              name: soil-sensor-base-config
              key: SENSOR_MAX_INTERVAL
        - name: Sensor__Location
          value: "q2"
        - name: Sensor__SensorId
          value: "soil-monitor-q2-001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soil-sensor-q3-001
  namespace: soil-sensor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soil-sensor-q3-001
  template:
    metadata:
      labels:
        app: soil-sensor-q3-001
    spec:
      containers:
      - name: soil-sensor
        image: fariaass/soil-sensor:v1.0
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
        env:
        - name: Sensor__MinIntervalSeconds
          valueFrom:
            configMapKeyRef:
              name: soil-sensor-base-config
              key: SENSOR_MIN_INTERVAL
        - name: Sensor__MaxIntervalSeconds
          valueFrom:
            configMapKeyRef:
              name: soil-sensor-base-config
              key: SENSOR_MAX_INTERVAL
        - name: Sensor__Location
          value: "q3"
        - name: Sensor__SensorId
          value: "soil-monitor-q3-001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soil-sensor-q4-001
  namespace: soil-sensor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soil-sensor-q4-001
  template:
    metadata:
      labels:
        app: soil-sensor-q4-001
    spec:
      containers:
      - name: soil-sensor
        image: fariaass/soil-sensor:v1.0
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
        env:
        - name: Sensor__MinIntervalSeconds
          valueFrom:
            configMapKeyRef:
              name: soil-sensor-base-config
              key: SENSOR_MIN_INTERVAL
        - name: Sensor__MaxIntervalSeconds
          valueFrom:
            configMapKeyRef:
              name: soil-sensor-base-config
              key: SENSOR_MAX_INTERVAL
        - name: Sensor__Location
          value: "q4"
        - name: Sensor__SensorId
          value: "soil-monitor-q4-001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
