apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: soil-sensor-system
type: Opaque
data:
  RABBITMQ_HOST: cmFiYml0bXEucmFiYml0bXUuc3ZjLmNsdXN0ZXIubG9jYWw=  # rabbitmq.rabbitmq.svc.cluster.local
  RABBITMQ_PORT: NTY3Mg==  # 5672
  RABBITMQ_USERNAME: Z3Vlc3Q=  # guest
  RABBITMQ_PASSWORD: Z3Vlc3Q=  # guest