apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: soil-sensor-system
type: Opaque
stringData:
  RABBITMQ_HOST: rabbitmq.rabbitmq.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: user
  RABBITMQ_PASSWORD: password
