apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-service-config
  namespace: aggregator-service
data:
  INPUT_QUEUE: "soil-moisture-data"
  OUTPUT_QUEUE: "soil-moisture-sensors"
  AGGREGATION_INTERVAL_SECONDS: "10"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
